/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

/**
 *
 * @author Jarno Matarmaa ( University of Tampere )
 */
public class MultiTimer extends javax.swing.JFrame {

    /**
     * Creates new form MultiTimer
     */
    public MultiTimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StopWatch1 = new javax.swing.JLabel();
        StopWatch3 = new javax.swing.JLabel();
        StopWatch4 = new javax.swing.JLabel();
        StopWatch2 = new javax.swing.JLabel();
        StopWatch5 = new javax.swing.JLabel();
        StopWatch6 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        PlayerTag3 = new javax.swing.JLabel();
        PlayerTag2 = new javax.swing.JLabel();
        PlayerTag4 = new javax.swing.JLabel();
        PlayerTag1 = new javax.swing.JLabel();
        PlayerTag6 = new javax.swing.JLabel();
        PlayerTag5 = new javax.swing.JLabel();
        RunSW3 = new javax.swing.JButton();
        RunSW1 = new javax.swing.JButton();
        RunSW5 = new javax.swing.JButton();
        StopSW2 = new javax.swing.JButton();
        StopSW4 = new javax.swing.JButton();
        StopSW6 = new javax.swing.JButton();
        StopSW1 = new javax.swing.JButton();
        RunSW2 = new javax.swing.JButton();
        StopSW3 = new javax.swing.JButton();
        RunSW4 = new javax.swing.JButton();
        StopSW5 = new javax.swing.JButton();
        RunSW6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StopWatch1.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch1.setText("00:00,0");

        StopWatch3.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch3.setText("00:00,0");

        StopWatch4.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch4.setText("00:00,0");

        StopWatch2.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch2.setText("00:00,0");

        StopWatch5.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch5.setText("00:00,0");

        StopWatch6.setFont(new java.awt.Font("Lucida Grande", 0, 100)); // NOI18N
        StopWatch6.setText("00:00,0");

        jProgressBar1.setSize(new java.awt.Dimension(146, 60));

        jProgressBar2.setSize(new java.awt.Dimension(146, 60));

        jProgressBar3.setSize(new java.awt.Dimension(146, 60));

        jProgressBar4.setSize(new java.awt.Dimension(146, 60));

        jProgressBar5.setSize(new java.awt.Dimension(146, 60));

        jProgressBar6.setSize(new java.awt.Dimension(146, 60));

        PlayerTag3.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag3.setText("Player 3");

        PlayerTag2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag2.setText("Player 2");

        PlayerTag4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag4.setText("Player 4");

        PlayerTag1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag1.setText("Player 1");

        PlayerTag6.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag6.setText("Player 6");

        PlayerTag5.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        PlayerTag5.setText("Player 5");

        RunSW3.setText("Play");

        RunSW1.setBackground(new java.awt.Color(0, 204, 102));
        RunSW1.setText("Play");
        RunSW1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BGC symbol.png"))); // NOI18N
        RunSW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunSW1ActionPerformed(evt);
            }
        });

        RunSW5.setText("Play");

        StopSW2.setBackground(new java.awt.Color(255, 153, 51));
        StopSW2.setText("Stop");
        StopSW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopSW2ActionPerformed(evt);
            }
        });

        StopSW4.setText("Stop");

        StopSW6.setText("Stop");

        StopSW1.setText("Stop");
        StopSW1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopSW1ActionPerformed(evt);
            }
        });

        RunSW2.setText("Play");
        RunSW2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunSW2ActionPerformed(evt);
            }
        });

        StopSW3.setText("Stop");
        StopSW3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopSW3ActionPerformed(evt);
            }
        });

        RunSW4.setText("Play");
        RunSW4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunSW4ActionPerformed(evt);
            }
        });

        StopSW5.setText("Stop");
        StopSW5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopSW5ActionPerformed(evt);
            }
        });

        RunSW6.setText("Play");
        RunSW6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunSW6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopWatch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopWatch5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RunSW5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlayerTag5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(RunSW3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(RunSW1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PlayerTag1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PlayerTag3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StopWatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopWatch4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopWatch6, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(PlayerTag2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RunSW2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW2))
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PlayerTag4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RunSW4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW4))
                        .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PlayerTag6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RunSW6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(StopSW6))
                        .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StopWatch2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PlayerTag2, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(RunSW2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StopSW2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PlayerTag1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(StopSW1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RunSW1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(StopWatch4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StopWatch3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PlayerTag3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlayerTag4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RunSW3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StopSW3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StopSW4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RunSW4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StopWatch5)
                    .addComponent(StopWatch6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PlayerTag6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PlayerTag5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RunSW5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(StopSW5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StopSW6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RunSW6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RunSW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunSW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunSW1ActionPerformed

    private void StopSW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopSW2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopSW2ActionPerformed

    private void StopSW1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopSW1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopSW1ActionPerformed

    private void RunSW2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunSW2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunSW2ActionPerformed

    private void StopSW3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopSW3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopSW3ActionPerformed

    private void RunSW4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunSW4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunSW4ActionPerformed

    private void StopSW5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopSW5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StopSW5ActionPerformed

    private void RunSW6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunSW6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RunSW6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiTimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PlayerTag1;
    private javax.swing.JLabel PlayerTag2;
    private javax.swing.JLabel PlayerTag3;
    private javax.swing.JLabel PlayerTag4;
    private javax.swing.JLabel PlayerTag5;
    private javax.swing.JLabel PlayerTag6;
    private javax.swing.JButton RunSW1;
    private javax.swing.JButton RunSW2;
    private javax.swing.JButton RunSW3;
    private javax.swing.JButton RunSW4;
    private javax.swing.JButton RunSW5;
    private javax.swing.JButton RunSW6;
    private javax.swing.JButton StopSW1;
    private javax.swing.JButton StopSW2;
    private javax.swing.JButton StopSW3;
    private javax.swing.JButton StopSW4;
    private javax.swing.JButton StopSW5;
    private javax.swing.JButton StopSW6;
    private javax.swing.JLabel StopWatch1;
    private javax.swing.JLabel StopWatch2;
    private javax.swing.JLabel StopWatch3;
    private javax.swing.JLabel StopWatch4;
    private javax.swing.JLabel StopWatch5;
    private javax.swing.JLabel StopWatch6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    // End of variables declaration//GEN-END:variables
}
